### PR TITLE
Fix/formatting

### PR DESCRIPTION
**Pull request by hcw70**
Changes
* Formatting fixed for code blocks.
* Rendering of parameter list fixed. Occured twice, once without formatting.
* Fixed rendering of class with multiple bases where some were not found in current doxygen scope.
* Repeat method brief description in front of detailed description for functions. Use brief in overview, brief+detailed in detailed view.
* Added rendering of enclosed types (struct A { using B=int; };) (see test/templated-base)

Pls provide feedback on the approaches taken, since some things are still somewhat 
unclear, esp. link generation and referencing.

### CODE REVIEW

**Comment by jason-fox** [comment]
@hcw70  Could you add a test-case under https://github.com/jason-fox/fox.jason.passthrough.doxygen/test so I can see what you are attempting to do here.

**Comment by hcw70** [comment]
@jason-fox There is no test folder in the repo...

**Comment by hcw70** [comment]
Ok, now how do i (simply) run the unit tests without setting up a runner / github workflow?

**Comment by jason-fox** [comment]
```console
dita install https://github.com/jason-fox/fox.jason.unit-test/archive/master.zip
```

```console
dita --format unit-test \
     --output out \
     --input ../plugins/fox.jason.passthrough.doxygen/test
```     

or just go into an individual test and run:

```console
ant
```

More info [here](https://jason-fox.github.io/dita-ot-plugins/unit-test).  

Since you have updated the format, many of your changes will produce false positives, but the diff report is still of interest.

**Comment by jason-fox** [comment]
> @jason-fox There was no test folder in the repo...
> But now (since 3h) there is...

The Java Source and the Unit Tests are removed as part of the release process. I hadn't performed the rollback to recover them.

**Comment by hcw70** [comment]
Ok i am struggling still. How are the "unneded" xml attributes removed prior to unit test diffing?
Is there a XSLT that i can use?

**Comment by hcw70** [comment]
Ok, i got somewhat away with this:

```
<?xml version="1.0" encoding="utf-8"?>
<!--
    Remove attributes not needed during unit test diffing
    (c) Hauke Wintjen, Freeware
-->
<xsl:stylesheet
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  version="2.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:instrument="http://jason.fox/xslt/instrument/"
  xmlns:lxslt="http://xml.apache.org/xslt"
  xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot"
  xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/"
  xmlns:saxon="http://saxon.sf.net/" 
  exclude-result-prefixes="dita-ot ditaarch saxon"
>

 <xsl:output method="xml" indent="yes" saxon:attribute-order="align colname"/>

    <!-- IdentityTransform -->
    <!-- Copy elements without NS, see https://stackoverflow.com/a/12466708 -->
    <xsl:template match="*" priority="-1">
       <xsl:element name="{name()}">
          <xsl:apply-templates select="node()|@*"/>
       </xsl:element>
    </xsl:template>
    
    <!-- Copy all other nodes -->
    <xsl:template match="node()|@*" priority="-2">
       <xsl:copy />      
    </xsl:template>

    <!-- Global remove some attribs -->
    <xsl:template match="@class|@domains|@xtrc">
    </xsl:template>


</xsl:stylesheet>

```

which removes the diffs to a minimum, so i can see some issues now.
However, how can i create the expected.xml as soon as i am happy, to make you happy?

**Comment by hcw70** [comment]
Issuing 
> ant -Dtest.copy=true
copies only the input doxygen xml to the expected. This is not what one wants.

I also am struggling with the unit tests, since most of them are failing because of (maybe unrelated to my changes)
diffs.
I would question the approach here of unit testing. 
Comparing the complete unformatted output with an expected.xml only helps to detect any changes.
But the changes may be related to 
* Formatting differences (spaces / newlines introduced in the XSLT)
* Additional / missing attributes (see my remove-attribs.xsl above)
* Other changes of the output unrelated to the unit test at hand.

So in order to have unit tests for this i would propose:
* Run remove-unneded-attribs on the output before comparing with expected.
* Run dita-pretty on the output before comparing with expected.
* Dont compare 1 to 1 with the expeced, but apply a set of xpath expressions 
    to the output to verify expectation.
* or as an alternative to xpath checking, cut out the relevant xml elements / attribs and compare that to expected.

I will continue to implement my formatting adaptions, but am unable to adapt the unit tests as they are currently,
since they dont make much sense in the way they are set up currently, and the diffs dont help much also. 
Pls support here.

**Comment by jason-fox** [comment]
Keep it simple. If a full unit-test doesn't make sense, just add a new `doxygen.xml` file into the tests folders which illustrates what you were trying to achieve, and I'll fix the test run later.

**Comment by hcw70** [comment]
Ok, i now reviewed the hand-formatted both expected and results of all tests.
IMHO they look ok. I have updated the initial message where i wrote the changes i did.

Some bugs are still open, but they i will fix with another pull request:
* Return types are not clickable / dont have correct names.
* Other links seem to be broken.

**Comment by hcw70** [comment]
@jason-fox Could you have a look?

**Comment by jason-fox** [comment]
@hcw70 - thank you very much for the improvements. You are right that the Unit Tests are for detecting changes, specifically when I regenerate `expectation.xml` it is much easier to see that the changes align with the proposals in the PR.  Don't worry too much if a PR breaks the tests, false positives will be fixed post merge. The  failures and the diffs help me to decide when to merge.

I have amended the approach of 7e73325 - the Global namespace is still created in the pre-processing, but a package `<topic>` is only rendered if a package contains a class, enum or interface directly. The other rendered changes are all valid improvements.

**Pull request merged**
